export const ANIME_TITLE_HEIGHT = 50;
export const BUTTON_SIZE = ANIME_TITLE_HEIGHT;
export const ROBOTO_MONO_HEIGHT_WIDHT_RATIO = 1.4;
export const LIST_ITEM_HEIGHT = 40;
export const LIST_ITEM_PADDING = 15;
